package com.citi.banking.config;

import com.citi.banking.model.*;
import com.citi.banking.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

@Component
@RequiredArgsConstructor
@Slf4j
public class DataSeeder implements CommandLineRunner {

    private final CustomerRepository customerRepository;
    private final AccountRepository accountRepository;
    private final TransactionRepository transactionRepository;
    private final CreditCardRepository creditCardRepository;
    private final BranchRepository branchRepository;
    private final LoanRepository loanRepository;

    @Override
    @Transactional
    public void run(String... args) {
        log.info("Seeding Citi Banking sample data...");

        List<Branch> branches = seedBranches();
        List<Customer> customers = seedCustomers();
        List<Account> accounts = seedAccounts(customers, branches);
        seedTransactions(accounts);
        seedCreditCards(customers);
        seedLoans(customers);

        log.info("Data seeding complete — {} customers, {} accounts, {} branches",
                customers.size(), accounts.size(), branches.size());
    }

    private List<Branch> seedBranches() {
        List<Branch> branches = List.of(
                Branch.builder()
                        .branchCode("NYC-001")
                        .branchName("Citi Flagship — Park Avenue")
                        .address("399 Park Avenue")
                        .city("New York")
                        .state("NY")
                        .zipCode("10022")
                        .phoneNumber("212-559-1000")
                        .branchType(Branch.BranchType.FULL_SERVICE)
                        .openTime(LocalTime.of(8, 0))
                        .closeTime(LocalTime.of(18, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(true)
                        .hasNotaryService(true)
                        .status(Branch.BranchStatus.OPEN)
                        .build(),
                Branch.builder()
                        .branchCode("NYC-002")
                        .branchName("Citi Wealth Center — Fifth Avenue")
                        .address("666 Fifth Avenue")
                        .city("New York")
                        .state("NY")
                        .zipCode("10103")
                        .phoneNumber("212-559-2000")
                        .branchType(Branch.BranchType.WEALTH_CENTER)
                        .openTime(LocalTime.of(9, 0))
                        .closeTime(LocalTime.of(17, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(true)
                        .hasNotaryService(true)
                        .status(Branch.BranchStatus.OPEN)
                        .build(),
                Branch.builder()
                        .branchCode("SF-001")
                        .branchName("Citi — Market Street")
                        .address("1 Sansome Street")
                        .city("San Francisco")
                        .state("CA")
                        .zipCode("94104")
                        .phoneNumber("415-627-6000")
                        .branchType(Branch.BranchType.FULL_SERVICE)
                        .openTime(LocalTime.of(9, 0))
                        .closeTime(LocalTime.of(17, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(false)
                        .hasNotaryService(true)
                        .status(Branch.BranchStatus.OPEN)
                        .build(),
                Branch.builder()
                        .branchCode("MIA-001")
                        .branchName("Citi Private Bank — Brickell")
                        .address("201 S Biscayne Blvd")
                        .city("Miami")
                        .state("FL")
                        .zipCode("33131")
                        .phoneNumber("305-347-1000")
                        .branchType(Branch.BranchType.PRIVATE_BANK)
                        .openTime(LocalTime.of(9, 0))
                        .closeTime(LocalTime.of(17, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(true)
                        .hasNotaryService(true)
                        .status(Branch.BranchStatus.OPEN)
                        .build(),
                Branch.builder()
                        .branchCode("CHI-001")
                        .branchName("Citi Express — Michigan Avenue")
                        .address("500 N Michigan Avenue")
                        .city("Chicago")
                        .state("IL")
                        .zipCode("60611")
                        .phoneNumber("312-627-3000")
                        .branchType(Branch.BranchType.EXPRESS)
                        .openTime(LocalTime.of(8, 0))
                        .closeTime(LocalTime.of(20, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(false)
                        .hasNotaryService(false)
                        .status(Branch.BranchStatus.OPEN)
                        .build(),
                Branch.builder()
                        .branchCode("DC-001")
                        .branchName("Citi Commercial — K Street")
                        .address("1101 K Street NW")
                        .city("Washington")
                        .state("DC")
                        .zipCode("20005")
                        .phoneNumber("202-879-6000")
                        .branchType(Branch.BranchType.COMMERCIAL)
                        .openTime(LocalTime.of(9, 0))
                        .closeTime(LocalTime.of(17, 0))
                        .hasAtm(true)
                        .hasSafeDeposit(false)
                        .hasNotaryService(true)
                        .status(Branch.BranchStatus.OPEN)
                        .build()
        );
        return branchRepository.saveAll(branches);
    }

    private List<Customer> seedCustomers() {
        List<Customer> customers = List.of(
                Customer.builder()
                        .firstName("James").lastName("Morgan")
                        .email("james.morgan@example.com").phoneNumber("212-555-0101")
                        .dateOfBirth(LocalDate.of(1975, 3, 15))
                        .ssn("***-**-1001")
                        .address("200 E 82nd Street").city("New York").state("NY").zipCode("10028")
                        .segment(Customer.CustomerSegment.CITIGOLD_PRIVATE_CLIENT)
                        .build(),
                Customer.builder()
                        .firstName("Maria").lastName("Santos")
                        .email("maria.santos@example.com").phoneNumber("415-555-0102")
                        .dateOfBirth(LocalDate.of(1982, 7, 22))
                        .ssn("***-**-1002")
                        .address("1500 Bay Street").city("San Francisco").state("CA").zipCode("94123")
                        .segment(Customer.CustomerSegment.CITIGOLD)
                        .build(),
                Customer.builder()
                        .firstName("Robert").lastName("Chen")
                        .email("robert.chen@example.com").phoneNumber("312-555-0103")
                        .dateOfBirth(LocalDate.of(1990, 11, 8))
                        .ssn("***-**-1003")
                        .address("875 N Michigan Avenue").city("Chicago").state("IL").zipCode("60611")
                        .segment(Customer.CustomerSegment.CITI_PRIORITY)
                        .build(),
                Customer.builder()
                        .firstName("Sarah").lastName("Williams")
                        .email("sarah.williams@example.com").phoneNumber("305-555-0104")
                        .dateOfBirth(LocalDate.of(1988, 1, 30))
                        .ssn("***-**-1004")
                        .address("900 Brickell Key Blvd").city("Miami").state("FL").zipCode("33131")
                        .segment(Customer.CustomerSegment.RETAIL)
                        .build(),
                Customer.builder()
                        .firstName("David").lastName("Patel")
                        .email("david.patel@example.com").phoneNumber("202-555-0105")
                        .dateOfBirth(LocalDate.of(1970, 5, 12))
                        .ssn("***-**-1005")
                        .address("1600 Pennsylvania Ave").city("Washington").state("DC").zipCode("20006")
                        .segment(Customer.CustomerSegment.COMMERCIAL)
                        .build(),
                Customer.builder()
                        .firstName("Emily").lastName("Johnson")
                        .email("emily.johnson@example.com").phoneNumber("212-555-0106")
                        .dateOfBirth(LocalDate.of(1995, 9, 3))
                        .ssn("***-**-1006")
                        .address("350 W 42nd Street").city("New York").state("NY").zipCode("10036")
                        .segment(Customer.CustomerSegment.RETAIL)
                        .build(),
                Customer.builder()
                        .firstName("Michael").lastName("Thompson")
                        .email("michael.thompson@example.com").phoneNumber("415-555-0107")
                        .dateOfBirth(LocalDate.of(1968, 12, 18))
                        .ssn("***-**-1007")
                        .address("2000 Pacific Avenue").city("San Francisco").state("CA").zipCode("94115")
                        .segment(Customer.CustomerSegment.CITIGOLD)
                        .build(),
                Customer.builder()
                        .firstName("Lisa").lastName("Kim")
                        .email("lisa.kim@example.com").phoneNumber("312-555-0108")
                        .dateOfBirth(LocalDate.of(1985, 4, 25))
                        .ssn("***-**-1008")
                        .address("233 E Wacker Drive").city("Chicago").state("IL").zipCode("60601")
                        .segment(Customer.CustomerSegment.CITI_PRIORITY)
                        .build()
        );
        return customerRepository.saveAll(customers);
    }

    private List<Account> seedAccounts(List<Customer> customers, List<Branch> branches) {
        List<Account> accounts = List.of(
                // James Morgan — Citigold Private Client
                Account.builder()
                        .accountNumber("CITI-CHK-100001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("245830.50"))
                        .availableBalance(new BigDecimal("245830.50"))
                        .currency("USD")
                        .customer(customers.get(0))
                        .branchCode(branches.get(0).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-SAV-100002")
                        .accountType(Account.AccountType.SAVINGS)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("1250000.00"))
                        .availableBalance(new BigDecimal("1250000.00"))
                        .currency("USD")
                        .customer(customers.get(0))
                        .branchCode(branches.get(1).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-MMA-100003")
                        .accountType(Account.AccountType.MONEY_MARKET)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("500000.00"))
                        .availableBalance(new BigDecimal("500000.00"))
                        .currency("USD")
                        .customer(customers.get(0))
                        .branchCode(branches.get(1).getBranchCode())
                        .build(),
                // Maria Santos — Citigold
                Account.builder()
                        .accountNumber("CITI-CHK-200001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("78540.25"))
                        .availableBalance(new BigDecimal("78540.25"))
                        .currency("USD")
                        .customer(customers.get(1))
                        .branchCode(branches.get(2).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-SAV-200002")
                        .accountType(Account.AccountType.SAVINGS)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("350000.00"))
                        .availableBalance(new BigDecimal("350000.00"))
                        .currency("USD")
                        .customer(customers.get(1))
                        .branchCode(branches.get(2).getBranchCode())
                        .build(),
                // Robert Chen — Citi Priority
                Account.builder()
                        .accountNumber("CITI-CHK-300001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("32150.75"))
                        .availableBalance(new BigDecimal("32150.75"))
                        .currency("USD")
                        .customer(customers.get(2))
                        .branchCode(branches.get(4).getBranchCode())
                        .build(),
                // Sarah Williams — Retail
                Account.builder()
                        .accountNumber("CITI-CHK-400001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("5420.88"))
                        .availableBalance(new BigDecimal("5420.88"))
                        .currency("USD")
                        .customer(customers.get(3))
                        .branchCode(branches.get(3).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-SAV-400002")
                        .accountType(Account.AccountType.SAVINGS)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("15000.00"))
                        .availableBalance(new BigDecimal("15000.00"))
                        .currency("USD")
                        .customer(customers.get(3))
                        .branchCode(branches.get(3).getBranchCode())
                        .build(),
                // David Patel — Commercial
                Account.builder()
                        .accountNumber("CITI-BIZ-500001")
                        .accountType(Account.AccountType.BUSINESS_CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("892750.00"))
                        .availableBalance(new BigDecimal("892750.00"))
                        .currency("USD")
                        .customer(customers.get(4))
                        .branchCode(branches.get(5).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-BIZ-500002")
                        .accountType(Account.AccountType.BUSINESS_SAVINGS)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("2150000.00"))
                        .availableBalance(new BigDecimal("2150000.00"))
                        .currency("USD")
                        .customer(customers.get(4))
                        .branchCode(branches.get(5).getBranchCode())
                        .build(),
                // Emily Johnson — Retail
                Account.builder()
                        .accountNumber("CITI-CHK-600001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("3250.40"))
                        .availableBalance(new BigDecimal("3250.40"))
                        .currency("USD")
                        .customer(customers.get(5))
                        .branchCode(branches.get(0).getBranchCode())
                        .build(),
                // Michael Thompson — Citigold
                Account.builder()
                        .accountNumber("CITI-CHK-700001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("125800.00"))
                        .availableBalance(new BigDecimal("125800.00"))
                        .currency("USD")
                        .customer(customers.get(6))
                        .branchCode(branches.get(2).getBranchCode())
                        .build(),
                Account.builder()
                        .accountNumber("CITI-CD-700002")
                        .accountType(Account.AccountType.CERTIFICATE_OF_DEPOSIT)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("100000.00"))
                        .availableBalance(new BigDecimal("0.00"))
                        .currency("USD")
                        .customer(customers.get(6))
                        .branchCode(branches.get(2).getBranchCode())
                        .build(),
                // Lisa Kim — Citi Priority
                Account.builder()
                        .accountNumber("CITI-CHK-800001")
                        .accountType(Account.AccountType.CHECKING)
                        .status(Account.AccountStatus.ACTIVE)
                        .balance(new BigDecimal("41200.60"))
                        .availableBalance(new BigDecimal("41200.60"))
                        .currency("USD")
                        .customer(customers.get(7))
                        .branchCode(branches.get(4).getBranchCode())
                        .build()
        );
        return accountRepository.saveAll(accounts);
    }

    private void seedTransactions(List<Account> accounts) {
        Account jamesChecking = accounts.get(0);
        Account mariaSavings = accounts.get(4);
        Account robertChecking = accounts.get(5);
        Account sarahChecking = accounts.get(6);
        Account davidBiz = accounts.get(8);
        Account emilyChecking = accounts.get(10);

        List<Transaction> transactions = List.of(
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(jamesChecking)
                        .type(Transaction.TransactionType.WIRE_TRANSFER)
                        .amount(new BigDecimal("50000.00"))
                        .balanceAfter(new BigDecimal("295830.50"))
                        .description("Wire transfer from Morgan Stanley brokerage")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("Morgan Stanley")
                        .channel(Transaction.TransactionChannel.WIRE)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(jamesChecking)
                        .type(Transaction.TransactionType.BILL_PAYMENT)
                        .amount(new BigDecimal("4200.00"))
                        .balanceAfter(new BigDecimal("241630.50"))
                        .description("Monthly mortgage payment — 200 E 82nd St")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("CitiMortgage")
                        .channel(Transaction.TransactionChannel.ONLINE)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(jamesChecking)
                        .type(Transaction.TransactionType.POS_PURCHASE)
                        .amount(new BigDecimal("385.50"))
                        .balanceAfter(new BigDecimal("245445.00"))
                        .description("Daniel — Fine Dining, Upper East Side")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .channel(Transaction.TransactionChannel.BRANCH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(mariaSavings)
                        .type(Transaction.TransactionType.INTEREST_CREDIT)
                        .amount(new BigDecimal("1458.33"))
                        .balanceAfter(new BigDecimal("351458.33"))
                        .description("Monthly interest credit — Citi Accelerate Savings")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .channel(Transaction.TransactionChannel.ACH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(mariaSavings)
                        .type(Transaction.TransactionType.TRANSFER_OUT)
                        .amount(new BigDecimal("5000.00"))
                        .balanceAfter(new BigDecimal("345000.00"))
                        .description("Transfer to checking account")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyAccount("CITI-CHK-200001")
                        .channel(Transaction.TransactionChannel.MOBILE)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(robertChecking)
                        .type(Transaction.TransactionType.ACH_CREDIT)
                        .amount(new BigDecimal("6850.00"))
                        .balanceAfter(new BigDecimal("39000.75"))
                        .description("Payroll deposit — Accenture")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("Accenture LLP")
                        .channel(Transaction.TransactionChannel.ACH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(robertChecking)
                        .type(Transaction.TransactionType.ATM_WITHDRAWAL)
                        .amount(new BigDecimal("500.00"))
                        .balanceAfter(new BigDecimal("31650.75"))
                        .description("ATM withdrawal — Michigan Ave Citi ATM")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .channel(Transaction.TransactionChannel.ATM)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(sarahChecking)
                        .type(Transaction.TransactionType.ACH_CREDIT)
                        .amount(new BigDecimal("3200.00"))
                        .balanceAfter(new BigDecimal("8620.88"))
                        .description("Payroll deposit — Baptist Health South Florida")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("Baptist Health")
                        .channel(Transaction.TransactionChannel.ACH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(sarahChecking)
                        .type(Transaction.TransactionType.BILL_PAYMENT)
                        .amount(new BigDecimal("1850.00"))
                        .balanceAfter(new BigDecimal("3570.88"))
                        .description("Rent payment — Brickell Key apartments")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("Brickell Key Management")
                        .channel(Transaction.TransactionChannel.ONLINE)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(davidBiz)
                        .type(Transaction.TransactionType.WIRE_TRANSFER)
                        .amount(new BigDecimal("150000.00"))
                        .balanceAfter(new BigDecimal("1042750.00"))
                        .description("Client payment — Federal consulting contract Q2")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("US Department of Commerce")
                        .channel(Transaction.TransactionChannel.WIRE)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(davidBiz)
                        .type(Transaction.TransactionType.ACH_DEBIT)
                        .amount(new BigDecimal("45000.00"))
                        .balanceAfter(new BigDecimal("847750.00"))
                        .description("Payroll processing — Patel Consulting Group")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("ADP Payroll Services")
                        .channel(Transaction.TransactionChannel.ACH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(emilyChecking)
                        .type(Transaction.TransactionType.ACH_CREDIT)
                        .amount(new BigDecimal("2800.00"))
                        .balanceAfter(new BigDecimal("6050.40"))
                        .description("Payroll deposit — Publicis Groupe")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .counterpartyName("Publicis Groupe")
                        .channel(Transaction.TransactionChannel.ACH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(emilyChecking)
                        .type(Transaction.TransactionType.POS_PURCHASE)
                        .amount(new BigDecimal("127.85"))
                        .balanceAfter(new BigDecimal("3122.55"))
                        .description("Whole Foods Market — Times Square")
                        .status(Transaction.TransactionStatus.COMPLETED)
                        .channel(Transaction.TransactionChannel.BRANCH)
                        .build(),
                Transaction.builder()
                        .transactionId(UUID.randomUUID().toString())
                        .account(emilyChecking)
                        .type(Transaction.TransactionType.TRANSFER_OUT)
                        .amount(new BigDecimal("500.00"))
                        .balanceAfter(new BigDecimal("2750.40"))
                        .description("Zelle transfer to roommate")
                        .status(Transaction.TransactionStatus.PENDING)
                        .counterpartyName("Ashley Rivera")
                        .channel(Transaction.TransactionChannel.MOBILE)
                        .build()
        );
        transactionRepository.saveAll(transactions);
    }

    private void seedCreditCards(List<Customer> customers) {
        List<CreditCard> cards = List.of(
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX1001")
                        .cardProduct(CreditCard.CardProduct.CITI_STRATA_PREMIER)
                        .customer(customers.get(0))
                        .creditLimit(new BigDecimal("50000.00"))
                        .currentBalance(new BigDecimal("8234.56"))
                        .availableCredit(new BigDecimal("41765.44"))
                        .apr(new BigDecimal("21.24"))
                        .minimumPaymentDue(new BigDecimal("165.00"))
                        .paymentDueDate(LocalDate.now().plusDays(15))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2028, 12, 31))
                        .rewardPoints(new BigDecimal("142500"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX2001")
                        .cardProduct(CreditCard.CardProduct.CITI_PREMIER)
                        .customer(customers.get(1))
                        .creditLimit(new BigDecimal("25000.00"))
                        .currentBalance(new BigDecimal("3150.20"))
                        .availableCredit(new BigDecimal("21849.80"))
                        .apr(new BigDecimal("20.99"))
                        .minimumPaymentDue(new BigDecimal("63.00"))
                        .paymentDueDate(LocalDate.now().plusDays(22))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2027, 8, 31))
                        .rewardPoints(new BigDecimal("67800"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX3001")
                        .cardProduct(CreditCard.CardProduct.CITI_DOUBLE_CASH)
                        .customer(customers.get(2))
                        .creditLimit(new BigDecimal("15000.00"))
                        .currentBalance(new BigDecimal("2475.80"))
                        .availableCredit(new BigDecimal("12524.20"))
                        .apr(new BigDecimal("19.74"))
                        .minimumPaymentDue(new BigDecimal("50.00"))
                        .paymentDueDate(LocalDate.now().plusDays(10))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2027, 5, 31))
                        .rewardPoints(new BigDecimal("0"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX4001")
                        .cardProduct(CreditCard.CardProduct.CITI_CUSTOM_CASH)
                        .customer(customers.get(3))
                        .creditLimit(new BigDecimal("8000.00"))
                        .currentBalance(new BigDecimal("1820.45"))
                        .availableCredit(new BigDecimal("6179.55"))
                        .apr(new BigDecimal("18.99"))
                        .minimumPaymentDue(new BigDecimal("36.00"))
                        .paymentDueDate(LocalDate.now().plusDays(18))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2028, 3, 31))
                        .rewardPoints(new BigDecimal("12400"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX5001")
                        .cardProduct(CreditCard.CardProduct.CITI_BUSINESS_PLATINUM)
                        .customer(customers.get(4))
                        .creditLimit(new BigDecimal("100000.00"))
                        .currentBalance(new BigDecimal("27500.00"))
                        .availableCredit(new BigDecimal("72500.00"))
                        .apr(new BigDecimal("17.99"))
                        .minimumPaymentDue(new BigDecimal("550.00"))
                        .paymentDueDate(LocalDate.now().plusDays(8))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2029, 1, 31))
                        .rewardPoints(new BigDecimal("89000"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX6001")
                        .cardProduct(CreditCard.CardProduct.COSTCO_ANYWHERE_VISA)
                        .customer(customers.get(5))
                        .creditLimit(new BigDecimal("5000.00"))
                        .currentBalance(new BigDecimal("945.30"))
                        .availableCredit(new BigDecimal("4054.70"))
                        .apr(new BigDecimal("20.49"))
                        .minimumPaymentDue(new BigDecimal("25.00"))
                        .paymentDueDate(LocalDate.now().plusDays(25))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2027, 11, 30))
                        .rewardPoints(new BigDecimal("3200"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX7001")
                        .cardProduct(CreditCard.CardProduct.CITI_REWARDS_PLUS)
                        .customer(customers.get(6))
                        .creditLimit(new BigDecimal("30000.00"))
                        .currentBalance(new BigDecimal("5890.00"))
                        .availableCredit(new BigDecimal("24110.00"))
                        .apr(new BigDecimal("20.24"))
                        .minimumPaymentDue(new BigDecimal("118.00"))
                        .paymentDueDate(LocalDate.now().plusDays(12))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2028, 6, 30))
                        .rewardPoints(new BigDecimal("45600"))
                        .build(),
                CreditCard.builder()
                        .cardNumber("4532XXXXXXXX8001")
                        .cardProduct(CreditCard.CardProduct.CITI_DIAMOND_PREFERRED)
                        .customer(customers.get(7))
                        .creditLimit(new BigDecimal("12000.00"))
                        .currentBalance(new BigDecimal("4200.00"))
                        .availableCredit(new BigDecimal("7800.00"))
                        .apr(new BigDecimal("0.00"))
                        .minimumPaymentDue(new BigDecimal("84.00"))
                        .paymentDueDate(LocalDate.now().plusDays(20))
                        .status(CreditCard.CardStatus.ACTIVE)
                        .expirationDate(LocalDate.of(2028, 9, 30))
                        .rewardPoints(new BigDecimal("0"))
                        .build()
        );
        creditCardRepository.saveAll(cards);
    }

    private void seedLoans(List<Customer> customers) {
        List<Loan> loans = List.of(
                Loan.builder()
                        .loanNumber("CITI-MTG-900001")
                        .customer(customers.get(0))
                        .loanType(Loan.LoanType.MORTGAGE)
                        .principalAmount(new BigDecimal("1200000.00"))
                        .outstandingBalance(new BigDecimal("985000.00"))
                        .interestRate(new BigDecimal("6.75"))
                        .termMonths(360)
                        .monthlyPayment(new BigDecimal("7783.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(5))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2021, 6, 15))
                        .maturityDate(LocalDate.of(2051, 6, 15))
                        .build(),
                Loan.builder()
                        .loanNumber("CITI-HEQ-900002")
                        .customer(customers.get(0))
                        .loanType(Loan.LoanType.HOME_EQUITY)
                        .principalAmount(new BigDecimal("200000.00"))
                        .outstandingBalance(new BigDecimal("142000.00"))
                        .interestRate(new BigDecimal("8.50"))
                        .termMonths(180)
                        .monthlyPayment(new BigDecimal("1970.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(5))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2022, 3, 1))
                        .maturityDate(LocalDate.of(2037, 3, 1))
                        .build(),
                Loan.builder()
                        .loanNumber("CITI-PER-900003")
                        .customer(customers.get(2))
                        .loanType(Loan.LoanType.PERSONAL)
                        .principalAmount(new BigDecimal("25000.00"))
                        .outstandingBalance(new BigDecimal("18750.00"))
                        .interestRate(new BigDecimal("10.99"))
                        .termMonths(60)
                        .monthlyPayment(new BigDecimal("543.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(12))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2023, 9, 1))
                        .maturityDate(LocalDate.of(2028, 9, 1))
                        .build(),
                Loan.builder()
                        .loanNumber("CITI-AUTO-900004")
                        .customer(customers.get(3))
                        .loanType(Loan.LoanType.AUTO)
                        .principalAmount(new BigDecimal("35000.00"))
                        .outstandingBalance(new BigDecimal("28400.00"))
                        .interestRate(new BigDecimal("5.49"))
                        .termMonths(72)
                        .monthlyPayment(new BigDecimal("573.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(18))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2024, 1, 15))
                        .maturityDate(LocalDate.of(2030, 1, 15))
                        .build(),
                Loan.builder()
                        .loanNumber("CITI-SBA-900005")
                        .customer(customers.get(4))
                        .loanType(Loan.LoanType.SMALL_BUSINESS)
                        .principalAmount(new BigDecimal("500000.00"))
                        .outstandingBalance(new BigDecimal("412000.00"))
                        .interestRate(new BigDecimal("7.25"))
                        .termMonths(120)
                        .monthlyPayment(new BigDecimal("5875.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(8))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2022, 8, 1))
                        .maturityDate(LocalDate.of(2032, 8, 1))
                        .build(),
                Loan.builder()
                        .loanNumber("CITI-STU-900006")
                        .customer(customers.get(5))
                        .loanType(Loan.LoanType.STUDENT)
                        .principalAmount(new BigDecimal("45000.00"))
                        .outstandingBalance(new BigDecimal("38200.00"))
                        .interestRate(new BigDecimal("4.99"))
                        .termMonths(120)
                        .monthlyPayment(new BigDecimal("477.00"))
                        .nextPaymentDate(LocalDate.now().plusDays(25))
                        .status(Loan.LoanStatus.CURRENT)
                        .originationDate(LocalDate.of(2023, 6, 1))
                        .maturityDate(LocalDate.of(2033, 6, 1))
                        .build()
        );
        loanRepository.saveAll(loans);
    }
}
